package org.fiuba.algotres.utils.enums;

public enum BattleState {
    NO_EMPEZADA,
    SELECCION_ACCION,
    SELECCION_HABILIDAD,
    SELECCION_ITEM,
    SELECCION_ITEM_VICTIMA,
    SELECCION_POKEMON,
    CONFIRMACION_RENDICION,
    ACCIONANDO
}
